services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=garage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  garage:
    build: .
    container_name: garage
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=garage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_SSL_MODE=disable
      - AUTH_KEY=secret-key
