services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=garage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password